### ISSUE TITLE
Motion + Voice <---> Fused Line #

### ISSUE THREAD

**Issue by beckybell13** [elainewlin/MusicBuddy#1]
- [x] Equation weighting each modality output to get a fused line #

- [x] Function getting y-coordinate (decimal from top of page) from the fused line #

- [x] Reset current line for motion and voice classes

**Comment by phoebetse** [comment]
Wrote very, very basic code on how to get y-coord from hard-coded line # (see fusedY.js). Whoever claims this task should use it :)

NOTE:  jquery selectors here (and elsewhere) will need to be changed when HTML changes

**Comment by phoebetse** [comment]
equation and structure for this fusion all implemented; still needs to undergo parameter testing though

- [ ] parameter testing (i.e. weights)
