### ISSUE TITLE
Gaze ---> y-coord

### ISSUE THREAD

**Issue by beckybell13** [elainewlin/MusicBuddy#2]
- [x] Make sure gaze class updates less frequently

**Comment by phoebetse** [comment]
edit: this is going to be done in trackGaze.js and fusedY.js

**Comment by phoebetse** [comment]
gaze updates every timestamp (can change it if i change the webgazer library, but decided to not). to deal with this, implemented preliminary smoothing function (average) that calls fuseY less frequently

current behavior: if FUSION_DEBUG === true:  if user is looking down for the past 3 seconds, will smallScroll()
